# Task configurations

interpret_task:
  agent: query_interpreter
  description: |
    Analyze the following user question and determine what data analysis needs to be performed.
    Identify relevant columns, filters, groupings, and calculations.
    
    Schema Information:
    {schema_info}
    
    User Question: {question}
    
    Provide your analysis in a structured format that identifies:
    1. Relevant columns to use
    2. Any filters or conditions
    3. Grouping requirements (if any)
    4. Calculations or aggregations needed
    5. Type of result expected (table, single value, etc.)
  expected_output: A structured analysis of the user's question with specific data requirements.

generate_code_task:
  agent: data_analyst_agent
  description: |
    Generate and execute python pandas code to answer the user's question based on the provided analysis.
    
    Schema Information:
    {schema_info}
    
    User Question: {question}
    Analysis: {analysis}
    
    1. Write clean, efficient pandas code that uses the '{dataset_name}' variable for the dataframe
    2. Include comments explaining your approach
    3. Execute the code using the code_interpreter tool
    4. Store both the code and execution results in variables named 'code' and 'result'
    5. Return both the code and execution results for the next task
  expected_output: Dictionary containing the generated code and its execution results
  context: [interpret_task]

explain_results_task:
  agent: result_explainer
  description: |
    Explain the provided analysis results in business-friendly language.
    
    User Question: {question}
    Analysis: {analysis}
    Results: {results}
    
    1. Format the results in a readable way
    2. Explain the findings in business terms that non-technical users can understand
    3. Highlight any interesting insights or patterns
    
    Your explanation should directly answer the original question.
  expected_output: Business-friendly explanation of the analysis results.
  context: [interpret_task, generate_code_task]