# Task configurations

interpret_task:
  agent: query_interpreter
  description: |
    Analyze the following user question and determine what data analysis needs to be performed.
    Identify relevant columns, filters, groupings, and calculations.
    
    Schema Information:
    {schema_info}
    
    User Question: {question}
    
    Provide your analysis in a structured format that identifies:
    1. Relevant columns to use
    2. Any filters or conditions
    3. Grouping requirements (if any)
    4. Calculations or aggregations needed
    5. Type of result expected (table, single value, etc.)
  expected_output: A structured analysis of the user's question with specific data requirements.

data_analyst_task:
  description: |
    You are a professional data analyst. Analyze the CSV data and answer the user's question clearly.
    
    User Question: {question}
    
    INSTRUCTIONS:
    1. FIRST: Load the CSV file from '/workspace/data/superstore.csv' and examine its structure
       - Print column names, data types, and first few rows to understand the data
    
    2. THEN: Analyze the data to answer the question
       - Write clear, focused code that directly addresses the question
       - Use pandas for data manipulation
       - Keep your code simple and efficient
    
    3. FINALLY: Present the findings in a clear, business-friendly way
       - Summarize key insights at the end
       - Format results in a readable manner
    
    IMPORTANT TECHNICAL GUIDELINES:
    - Run your code ONCE, examine the output, then provide your final answer
    - Do NOT use the Code Interpreter tool repeatedly
    - If you need visualization libraries, use only what's pre-installed
    - Keep your analysis in a SINGLE code block
    
    Your final answer should include:
    1. The code you used (with comments explaining your approach)
    2. The results of running that code
    3. A clear explanation of what the results mean
  expected_output: "Complete analysis with code, results, and explanation."
