# System Configuration

# Application settings
app:
  name: Business Analyst
  version: 0.1.0

# Data settings
data:
  default_dataset: superstore
  dataset_path: data/superstore.csv

# LLM Configuration
llm:
  default:
    # Using Google's Gemini model for all agents
    type: google
    model: gemini/gemini-2.0-flash
    temperature: 0
    max_tokens: 1000
  
  # Specific LLMs for different agents (optional)
  query_interpreter:
    # Inherits from default but with custom temperature
    type: google
    model: gemini/gemini-2.0-flash
    temperature: 0.2  # Slightly more creative for interpretation
  
  code_generator:
    # Specific LLM for code generation
    type: google
    model: gemini/gemini-2.0-flash
    temperature: 0  # Zero temperature for consistent code
  
  result_explainer:
    # Specific LLM for result explanation
    type: google
    model: gemini/gemini-2.0-flash
    temperature: 0.3  # More creativity for explanations

# Logging settings
logging:
  level: info
  file: logs/app.log